version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "phrases:1:1:compact"
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  publisher:
    container_name: publisher-service
    build:
      context: ./publisher/
      dockerfile: ./Dockerfile
    volumes:
      - ./publisher/src:/app/src
    depends_on:
      kafka:
        condition: service_healthy

  subscriber:
    container_name: subscriber-service
    build:
      context: ./subscriber/
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./subscriber/src:/app/src
    depends_on:
      kafka:
        condition: service_healthy

  client:
    container_name: client-service
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    depends_on:
      - subscriber
